config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :gigs, param: :uid do
    post :update_status
    resources :bids
    post :finish
    collection do
      get :search_all
    end
  end

  resources :users, param: :uid, only: [:show] do
    resources :reviews, only: [:new, :create, :show]
    resources :conversations do
      resources :messages, only: [:create]
    end
    collection do
      get :search_all
    end
  end

  get '/dashboard'  => 'users#dashboard'
  get '/about_us'   => 'pages#about_us'
  get '/howitworks' => 'pages#howitworks'
  
  post '/gigs/:gig_uid/bids/:bid_id/select_bid'   => 'gigs#select_bid',   as: :select_bid
  post '/gigs/:gig_uid/bids/:bid_id/deselect_bid' => 'gigs#deselect_bid', as: :deselect_bid
  post '/users/update_searchable' => 'users#update_searchable', as: :update_searchable
  post '/user/:user_uid/messages' => 'messages#new_message', as: :user_messages
  delete '/image/:imageable_id' => 'images#destroy', as: :image_destroy

  root 'gigs#index'
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  include SharedMethods
  belongs_to :gig
  belongs_to :user

  validate :one_bid_per_gig
  validates :user_id, :gig_id, presence: true
  validates :amount, numericality: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  default_scope { where(archived: false) }

  def one_bid_per_gig
    if Bid.find_by(gig_id: self.id, user_id: user.id)
      errors.add(:base, "Cannot bid multiple times on one gig.")
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create]
  before_action :is_gig_owner?, only: %i[index edit update]

  def index
    @gig = Gig.find_by(uid: params[:gig_uid])
    @bids = @gig.bids
  end

  def new
    redirect_to gig_path(params[:gig_uid])
  end

  def create
    @gig = Gig.find_by(uid: params[:gig_uid])
    @bid = @gig.bids.new(bid_params.merge(user_id: current_user.id))
    if @bid.save
      BidMailer.receive_bid(current_user, @gig).deliver
      redirect_to gig_path(@gig.uid)
    else
      flash[:alert] = @bid.errors.full_messages.to_sentence
      redirect_to gig_path(@gig.uid)
    end
  end

  def show
    @gig = Gig.find_by(uid: params[:gig_uid])
  end

  def destroy
    @bid = Bid.find(params[:id])
    @bid.archive
    redirect_to dashboard_path
  end

  private
    def bid_params
      params.require(:bid).permit(:amount, :description)
    end

    def is_gig_owner?
      @gig = Gig.find_by(uid: params[:gig_uid])
      if @gig.user != current_user
        redirect_to root_path
        flash[:alert] = "You are not authorized to view this gig's bids."
      end
    end
end

app/views/bids/_bid_actions.html.erb
<% if gig.awarded_bid == bid.id  && !gig.finished? %>
  <a href="#" data-toggle="modal" data-target="#finishBid" class="btn btn-success btn-sm">Finish Gig</a>
  <%= link_to "Deselect", deselect_bid_path(gig.uid, bid), method: :post, class: "btn btn-danger btn-sm" %>
<% elsif gig.awarded_bid == nil && !gig.finished? %>
  <a href="#" data-toggle="modal" data-target="#selectBid" class="btn btn-primary btn-sm">Select Bid</a>
<% elsif gig.reviews.present? %>
  Gig completed!
<% else %>
  <a href="#" data-toggle="modal" data-target="#bidButton" class="btn btn-primary btn-sm">Write a Review</a>
<% end %>

<!-- Modal for bid button -->
<div class="modal fade" id="bidButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">You are bidding on <%= @gig.name %></h4>
      </div>
      <div class="modal-body">
        <%= form_for [bid.user, Review.new(gig_id: @gig.id)] do |f| %>
          <%= f.hidden_field :gig_id, value: @gig.id %>
          <%= f.hidden_field :reviewer, value: current_user.id %>
          <div class="form-group">
            <%= f.label :rating, "Rating" %>
            <%= f.number_field :rating, autofocus: true, value: 1, min: 1, max: 5, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :comment, "comment" %>
            <%= f.text_area :comment, rows: 10, class: "form-control" %>
          </div>

          <div class="divider"></div>

          <%= f.submit class: "btn btn-success btn-theme" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- end Modal for bid button -->

<!-- Modal for select bid button -->
<div class="modal fade" id="selectBid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">You are going to select bid by <%= bid.user.fullname.titleize %> of <%= number_to_currency(bid.amount) %></h4>
      </div>
      <div class="modal-body text-right">
        <%= link_to "Confirm", select_bid_path(gig.uid, bid), method: :post, class: "btn btn-success btn-sm" %>
      </div>
    </div>
  </div>
</div>
<!-- end Modal for select bid button -->

<!-- Modal for finish bid button -->
<div class="modal fade" id="finishBid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">You are going to finish this bid.</h4>
        <p>After you finish the bid, don't forget to review your bidder!</p>
      </div>
      <div class="modal-body text-right">
        <%= link_to "Finish Gig", gig_finish_path(gig.uid), method: :post, class: "btn btn-success btn-sm" %>
      </div>
    </div>
  </div>
</div>
<!-- end Modal for finish bid button -->

app/views/bids/index.html.erb
<div class="container">
  <h2>Bids for <%= link_to @gig.name, gig_path(@gig.uid) %></h2>
  <div class="row">
    <div class="col-lg-8">
      <% @bids.each do |bid| %>
        <div class="panel panel-default paper-shadow" data-z="0.5">
          <div class="panel-body">
            <div class="media media-clearfix-xs">
              <div class="media-body">
                <div class="col-lg-8">
                  <h4 class="text-headline margin-v-5-0"><a href="app-student-course.html"><%= link_to bid.user.fullname.titleize, user_path(bid.user.uid) %></a> <small>(<%= bid.user.username %>)</small></h4>
                </div>
                <div class="col-lg-4">
                  <span class="pull-right"><%= render partial: "bids/bid_actions", locals: { gig: @gig, bid: bid} %></span>
                  <a href="#" data-toggle="modal" data-target="#sendMessage" class="btn btn-primary btn-sm">Send a message</a>
                </div>
                <div class="col-lg-12">
                  <p class="small"><%= render_stars(bid.user.avg_rating) %></p>
                  <p><%= bid.description %></p>
                  <hr class="margin-v-8">
                  <div class="media v-middle">
                    <div class="media-body">
                      <h4><%= number_to_currency(bid.amount) %></h4>
                      <%= bid.created_at.strftime("%B %d, %Y") %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Modal for send message -->
        <div class="modal fade" id="sendMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Send <%= bid.user.firstname.capitalize %> a message</h4>
              </div>
              <div class="modal-body">
                <%= form_for :message, url: user_messages_path(bid.user.uid), method: :post do |f| %>
                  <div class="form-group">
                    <%= f.label :subject %>
                    <%= f.text_field :subject, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :body, "Message" %>
                    <%= f.text_area :body, rows: 10, class: "form-control" %>
                  </div>
                  <%= f.submit "Send Message", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- end Modal for send message -->
      <% end %>
    </div>
    <div class="col-lg-4">
      <h5>Sort by: Date Amount</h5>
    </div>
  </div>
</div>