config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :gigs, param: :uid do
    post :update_status
    resources :bids
    post :finish
    collection do
      get :search_all
    end
  end

  resources :users, param: :uid, only: [:show] do
    resources :reviews, only: [:new, :create, :show]
    resources :conversations do
      resources :messages, only: [:create]
    end
    collection do
      get :search_all
    end
  end

  get '/dashboard'  => 'users#dashboard'
  get '/about_us'   => 'pages#about_us'
  get '/howitworks' => 'pages#howitworks'
  
  post '/gigs/:gig_uid/bids/:bid_id/select_bid'   => 'gigs#select_bid',   as: :select_bid
  post '/gigs/:gig_uid/bids/:bid_id/deselect_bid' => 'gigs#deselect_bid', as: :deselect_bid
  post '/users/update_searchable' => 'users#update_searchable', as: :update_searchable
  post '/user/:user_uid/messages' => 'messages#new_message', as: :user_messages
  delete '/image/:imageable_id' => 'images#destroy', as: :image_destroy

  root 'gigs#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :gigs
  has_many :bids
  has_many :reviews
  has_many :messages

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 20}
  validate :validate_username

  default_scope { where(archived: false) }
  before_create :set_uid

  geocoded_by :location
  after_validation :geocode

  searchkick rating: [:rating], locations: [:location]

  attr_accessor :login

  def set_uid
    self.uid = rand(100000000..999999990)
  end

  def search_data
    {
      firstname: firstname,
      lastname: lastname,
      rating: self.avg_rating.to_i,
      searchable: searchable,
    }.merge(location: {lat: latitude, lon: longitude})
  end

  def fullname
    [firstname, lastname].join(" ")
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.search_all(params)
    latitude = Geocoder.search(params[:location])[0].latitude if !Geocoder.search(params[:location]).empty?
    longitude = Geocoder.search(params[:location])[0].longitude if !Geocoder.search(params[:location]).empty?
    query = params[:search].nil? || params[:search].empty? ? "*" : params[:search]
    users = User.search(query, where: { location: { near: { lat: latitude, lon: longitude }, within: "25mi" },
                                        rating: { gte: params[:rating].to_i },
                                        searchable: true
                                      })
  end

  def avg_rating
    self.reviews.average(:rating).round(1) if self.reviews.present?
  end

  def conversation_count
    Conversation.where("sender_id = ? OR recipient_id = ?", self.id, self.id).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, only: %i[dashboard]

  def show
    @user = User.find_by(uid: params[:uid])
    @reviews = @user.reviews.order(created_at: :desc)
  end

  def update_searchable
    current_user.update_attribute(:searchable, params[:searchable])
    render nothing: true
  end

  def search_all
    params[:location] = "Minneapolis" if params[:location].nil? || params[:location].empty?
    @search_users = User.search_all(params)
    @users = User.where(id: @search_users.map(&:id)).page(params[:page]).per(25)
  end

  def dashboard
    @gigs = Gig.where(user_id: current_user).order(created_at: :desc)
    @bids = Bid.where(user: current_user).order(created_at: :asc)
  end

end

app/views/users/_gig_actions.html.erb
<% if gig.finished? %>
  Finished!
<% else %>
  <div class="btn-group">
    <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu dropdown-menu-right" role="menu">
      <li><%= link_to "Edit Gig", edit_gig_path(gig.uid) %></li>
      <li><%= link_to "View Bids", gig_bids_path(gig.uid) %></li>

      <% if gig.open? %>
        <li><%= link_to "Pause gig", gig_update_status_path(gig.uid, { status: 3 }), method: :post %></li>
      <% elsif gig.paused? %>
        <li><%= link_to "Open gig", gig_update_status_path(gig.uid, { status: 0 }), method: :post %></li>
      <% end %>

      <li class="divider"></li>
      <li><%= link_to "Delete Gig", gig_path(gig.uid), method: :delete, data: { confirm: "Are you sure?" } %></li>
      </li>
    </ul>
  </div>
<% end %>

app/views/users/_send_message.html.erb
<% if current_user.nil? %>
  <%= link_to "Login to send a message", new_user_session_path, class: "btn btn-line soft btn-theme btn-pill btn-block" %>
<% elsif current_user != @user %>
  <a href="#" data-toggle="modal" data-target="#sendMessage" class="btn btn-line soft btn-theme btn-pill btn-block">Send a message</a>
<% else %>
  <%= link_to "Go to your profile", dashboard_path, class: "btn btn-line soft  btn-theme btn-pill btn-block" %>
<% end %>

app/views/users/dashboard.html.erb
<div id="page-wrapper">
  <div class="container-fluid">

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
        <!-- Bootstrap Switch -->
        <div class="bootstrap-switch-container">
          <span class="bootstrap-switch-handle-on bootstrap-switch-primary" style="width: 33px;"></span>
          <span class="bootstrap-switch-handle-off bootstrap-switch-default" style="width: 33px;"></span>
          <input id="switch-size" name="searchable" type="checkbox" data-size="mini" data-on-text="Yes" data-off-text="No"
                 <%= current_user.searchable? ? "checked=" : nil %>>
          Allow your profile to be searchable? <i>Typically want this to be "Yes" so people can find you for their gigs.</i>
        </div>
        <br />

      </div>
    </div>

    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-comments fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= current_user.conversation_count %></div>
                <div>Your Messages</div>
              </div>
            </div>
          </div>
          <%= link_to user_conversations_path(current_user.uid) do %>
            <div class="panel-footer">
              <span class="pull-left">View Details</span>
              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
              <div class="clearfix"></div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-user fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge">&nbsp;</div>
                <div>Your Profile</div>
              </div>
            </div>
          </div>
          <%= link_to user_path(current_user.uid) do %>
            <div class="panel-footer">
              <span class="pull-left">View Details</span>
              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
              <div class="clearfix"></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Your Gigs</h3>
          </div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Project</th>
                    <th>Bids</th>
                    <th>Date Posted</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @gigs.each do |gig| %>
                    <tr>
                      <th scope="row"><%= gig.uid %></th>
                      <td><%= link_to truncate(gig.name, length: 40), gig_path(gig.uid) %></td>
                      <td><span class="label label-info"><%= link_to gig.bids.count, gig_bids_path(gig.uid), class: "button" %></span></td>
                      <td><%= gig.created_at.strftime("%B %d, %Y") %></td>
                      <td><%= gig.status %></td>
                      <td>
                        <%= render partial: "users/gig_actions", locals: { gig: gig } %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Your Bids</h3>
          </div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Gig Name</th>
                    <th>Date You bid</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @bids.each do |bid| %>
                    <tr>
                      <td><%= link_to bid.gig.name, gig_path(bid.gig.uid) %></td>
                      <td><%= bid.created_at.strftime("%B %d, %Y") %></td>
                      <td><%= bid.gig.status %></td>
                      <td>
                        <% if !bid.gig.finished? %>
                          <%#= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_gig_bid_path(bid.gig.uid, bid) %>
                          <%= link_to "<i class='fa fa-remove'></i> Undo Bid".html_safe, gig_bid_path(bid.gig.uid, bid), method: :delete, data: { confirm: "Are you sure?" } %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->
</div>

app/views/users/search_all.html.erb
<div class="main-header">
  <div class="container">
    <div class="row">

      <div class="col-md-10">
        <%= form_tag search_all_users_path, class: "form-search-list", method: :get do |f| %>
          <div class="row">
            <div class="col-lg-4 ">
              <div class="form-group">
                <label class="color-white">what <small>(gig keywords, skills, etc.)</small></label>
                <%= text_field_tag :search, nil, value: params[:search], class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <label class="color-white">where <small>(city, state, zipcode, etc.)</small></label>
                <%= text_field_tag :location, nil, value: params[:location], class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <label class="color-white">minimum rating</label>
                <%= select_tag :rating, options_for_select([0,1,2,3,4,5], params[:rating]), class: "form-control", style: "width: 100px;" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <label class="hidden-xs">&nbsp;</label>
                <%= submit_tag "Find users", class: "btn btn-block btn-theme btn-success" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="body-content clearfix">
  <div class="bg-color2">
    <div class="container">
      <div class="row">
        <div class="col-md-9">

          <div class="block-section-sm box-list-area">
            <div class="row hidden-xs">
              <div class="col-sm-6 ">
                <p><strong class="color-black"><%= params[:search] %> users near <%= params[:location] %></strong></p>
              </div>
              <div class="col-sm-6">
                <p class="text-right">Users 1 to <%= @users.count %> of <%= @users.total_count %></p>
              </div>
            </div>

            <!-- listing -->
            <div class="box-list">
              <% @users.each do |user| %>
                <div class="item">
                  <div class="row">
                    <div class="col-md-12">
                      <h3 class="no-margin-top"><%= link_to user.fullname.titleize, user_path(user.uid) %></h3>
                      <h5>
                        <%= user.reviews.count %> Reviews
                        <span class="rate"><%= render_stars(user.avg_rating) %></span>
                        <span class="color-white-mute"> <%= user.location %></span>
                      </h5>
                      <p><%= user.description %></p>
                      <span class="color-white-mute">
                        Last Logged In: <%= user.last_sign_in_at.nil? ? user.created_at.strftime("%b %d, %Y") : user.last_sign_in_at.strftime("%b %d, %Y") %>
                      </span>
                      <span class="pull-right"><%= link_to "Go to profile", user_path(user.uid), class: "btn btn-xs btn-theme btn-default" %></span>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>

            <!-- pagination -->
            <%= paginate @users %>

          </div><!-- end  box listing  -->
        </div>

        <div class="col-md-3">
          <div class="block-section-sm side-right">

            <!-- filter   -->
            <div class="row">
              <div class="col-xs-4">
                <p><strong>Sort by: </strong></p>
              </div>
              <div class="col-xs-8">
                <p class="text-right">
                  <strong>Rating</strong> - <a href="#" class="link-black"><strong>Last logged in</strong></a>
                </p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="body-content clearfix">
  <div class="bg-color1">
    <div class="container">
      <div class="col-md-3 col-sm-3">
        <div class="block-section text-center">
          <div class="white-space-20"></div>
          <h4>
            <%= @user.fullname.titleize %>
            <br>
            <small>(<%= @user.username %>)</small>
          </h4>
          <div class="white-space-20"></div>
          <ul class="list-unstyled">
            <li>(<%= @user.avg_rating %>) <%= render_stars(@user.avg_rating) %></li>
            <li><i class="fa fa-map-marker"></i> <%= @user.location %></li>
            <li>Last logged in <%= @user.last_sign_in_at.nil? ? @user.created_at.strftime("%b %d %Y") : @user.last_sign_in_at.strftime("%b %d %Y") %></li>
          </ul>
        </div>
        <%= @user.description %>
        <div class="white-space-20"></div>
        <%= render partial: "users/send_message" %>
      </div>
      <div class="col-md-9 col-sm-9">
        <div class="white-space-20"></div>
        <div class="block-section box-side-account">
          <h3 class="no-margin-top">Reviews</h3>
          <div class="">
            <table class="table">
              <% @user.reviews.each do |review| %>
                <tbody>
                  <tr>
                    <td width="150px;"><%= User.find(review.reviewer).fullname.titleize %></td>
                    <td><%= markdown(review.comment) %></td>
                    <td class="text-right" width="100px;"><%= render_stars(review.rating) %></td>
                  </tr>
                </tbody>
              <% end %>
            </table>
          </div>

          <!-- <nav>
            <ul class="pagination pagination-theme  ">
              <li>
                <a href="#" aria-label="Previous">
                <span aria-hidden="true">←</span>
                </a>
              </li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li>
                <a href="#" aria-label="Next">
                <span aria-hidden="true">→</span>
                </a>
              </li>
            </ul>
          </nav> -->

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal for send message -->
<div class="modal fade" id="sendMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send <%= @user.firstname.capitalize %> a message</h4>
      </div>
      <div class="modal-body">
        <%= form_for :message, url: user_messages_path(@user.uid), method: :post do |f| %>
          <div class="form-group">
            <%= f.label :subject %>
            <%= f.text_field :subject, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :body, "Message" %>
            <%= f.text_area :body, rows: 10, class: "form-control" %>
          </div>
          <%= f.submit "Send Message", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- end Modal for send message -->