config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :gigs, param: :uid do
    post :update_status
    resources :bids
    post :finish
    collection do
      get :search_all
    end
  end

  resources :users, param: :uid, only: [:show] do
    resources :reviews, only: [:new, :create, :show]
    resources :conversations do
      resources :messages, only: [:create]
    end
    collection do
      get :search_all
    end
  end

  get '/dashboard'  => 'users#dashboard'
  get '/about_us'   => 'pages#about_us'
  get '/howitworks' => 'pages#howitworks'
  
  post '/gigs/:gig_uid/bids/:bid_id/select_bid'   => 'gigs#select_bid',   as: :select_bid
  post '/gigs/:gig_uid/bids/:bid_id/deselect_bid' => 'gigs#deselect_bid', as: :deselect_bid
  post '/users/update_searchable' => 'users#update_searchable', as: :update_searchable
  post '/user/:user_uid/messages' => 'messages#new_message', as: :user_messages
  delete '/image/:imageable_id' => 'images#destroy', as: :image_destroy

  root 'gigs#index'
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  include SharedMethods
  belongs_to :category
  belongs_to :user
  has_many :bids
  has_many :reviews
  has_many :images, as: :imageable
  enum status: %w(open closed finished paused)

  validates :name, :description, :budget, :location, presence: true
  validates :budget, numericality: true
  validates :budget, numericality: { greater_than_or_equal_to: 0 }
  validate :max_images

  before_create :set_uid

  default_scope { where(archived: false) }

  geocoded_by :location
  after_validation :geocode

  searchkick locations: [:location]
  
  SEARCH_RATE = [5, 10, 15, 25, 50]

  def set_uid
    self.uid = rand(100000..999999)
  end

  def search_data
    attributes.merge location: {lat: latitude, lon: longitude}
  end

  def self.search_all(params)
    latitude = Geocoder.search(params[:location])[0].latitude if !Geocoder.search(params[:location]).empty?
    longitude = Geocoder.search(params[:location])[0].longitude if !Geocoder.search(params[:location]).empty?
    query = params[:search].empty? ? "*" : params[:search]
    gigs = Gig.search(query, fields: [:name, :description], where: { status: 0,
                                                                     budget: params[:min].to_i..99999,
                                                                     location: {
                                                                       near: { lat: latitude, lon: longitude }, within: "25mi"
                                                                     }
                                                                   },
                                                                   order: { created_at: :desc })
  end

  def max_images
    errors.add(:base, "Maximum images per gig is 5") if self.images.count > 4
  end

  def budget=(budget_str)
    value = budget_str.delete("$")
    write_attribute(:budget, value)
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!, only: %i[new create mygigs]
  before_action :is_gig_owner?, only: %i[edit update]
  before_action :gig_closed, only: %i[show edit update]

  def index
  end

  def new
    @gig = Gig.new
  end

  def create
    @gig = current_user.gigs.build(gig_params)
    build_image
    if @gig.save
      redirect_to gig_path(@gig.uid)
    else
      flash[:alert] = @gig.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @gig = find_gig
    @bid = Bid.new
    @bids = Bid.where(gig_id: @gig)
  end

  def edit
    @gig = find_gig
  end

  def update
    @gig = find_gig
    if @gig.update(gig_params)
      params[:gig][:image][:image].each { |img|  @gig.images.create(image: img) } if params[:gig][:image].present?
      redirect_to gig_path(@gig.uid)
    else
      flash[:alert] = @gig.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @gig = find_gig
    @gig.archive
    redirect_to dashboard_path
  end

  def search_all
    params[:location] = "Minneapolis" if params[:location].empty?
    @search_gigs = Gig.search_all(params)
    @sorted_gigs = Gig.where(id: @search_gigs.map(&:id)).order(sort_column + " " + sort_direction).page(params[:page]).per(25)
    @gigs = sort_category ? @sorted_gigs.where(category_id: params[:category]) : @sorted_gigs
  end

  def select_bid
    @gig = Gig.find_by(uid: params[:gig_uid])
    @gig.update(awarded_bid: params[:bid_id], status: 1)
    @bid = Bid.find(params[:bid_id])
    BidMailer.select_bid(@bid.user, @gig).deliver
    redirect_to gig_bids_path(@gig.uid)
  end

  def deselect_bid
    @gig = Gig.find_by(uid: params[:gig_uid])
    @gig.update(awarded_bid: nil, status: 0)
    redirect_to gig_bids_path(@gig.uid)
  end

  def finish
    @gig = Gig.find_by(uid: params[:gig_uid])
    @gig.update(status: 2)
    redirect_to gig_bids_path(@gig.uid)
  end

  def update_status
    @gig = Gig.find_by(uid: params[:gig_uid])
    @gig.update(status: params[:status].to_i)
    redirect_to dashboard_path
  end

  private

    def gig_params
      params.require(:gig).permit(:name, :description, :budget,
                                  :location, :status, :awarded_bid,
                                  :category_id, :location)
    end

    def find_gig
      Gig.find_by(uid: params[:uid])
    end

    def is_gig_owner?
      @gig = find_gig
      if @gig.user != current_user
        redirect_to root_path
        flash[:alert] = "You are not authorized to view this gig."
      end
    end

    def gig_closed
      @gig = find_gig
      if @gig.finished? && @gig.finished? && current_user != @gig.user
        flash[:alert] = "Gig is finished."
        redirect_to root_path
      end
    end

    def sort_column
      Gig.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def sort_category
      params[:category].present? && params[:category] != "All"
    end

    def build_image
      if params[:gig][:image].present?
        @gig.images.build(image: params[:gig][:image][:image])
      end
    end
end

app/views/gigs/_bid_button.html.erb
<% if current_user == gig.user %>
  <%= link_to "View bids", gig_bids_path(gig.uid), class: "btn btn-theme btn-t-primary btn-block-xs" %>
  <%= link_to "Edit gig", edit_gig_path(gig.uid), class: "btn btn-theme btn-t-primary btn-block-xs" %>
<% elsif user_signed_in? && current_user != gig.user && !gig.bids.where(user_id: current_user.id).exists? %>
  <a href="#" data-toggle="modal" data-target="#bidButton" class="btn btn-theme btn-t-primary btn-block-xs">Bid on this gig</a>
<% elsif current_user.present? && gig.bids.where(user_id: current_user.id).exists? %>
  <div class="btn btn-theme btn-line dark btn-block-xs">You bid on this gig already</div>
<% else %>
  <%= link_to "Bid on this Gig", new_gig_bid_path(@gig.uid), class: "btn btn-theme btn-t-primary btn-block-xs" %>
<% end %>

app/views/gigs/_gig_form.html.erb
<div class="body-content clearfix">
  <div class="bg-color2 block-section line-bottom">
    <div class="container">
      <h1 class="text-center no-margin"><%= form_name %></h1>
    </div>
  </div>

  <div class="bg-color1 block-section line-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <!-- form post a job -->
          <%= form_for(gig, url: url) do |f| %>
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
            <div class="form-group">
              <label>Description</label>
              <div class="color-white-mute"><small>Describe the responsibilities of this gig.</small></div>
              <%= f.text_area :description, rows: 10, class: "form-control" %>
            </div>
            <div class="form-group">
              <label>Category</label>
              <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: "form-control" %>
            </div>
            <div class="form-group">
              <div class="row clearfix">
                <div class="col-lg-6">
                  <label>Budget</label>
                  <%= f.text_field :budget, class: "form-control" %>
                </div>
                <div class="col-lg-6">
                  <label>Location</label>
                  <%= f.text_field :location, class: "form-control" %>
                </div>

              </div>
            </div>
            Upload images (up to 5 per gig)
            <%= f.fields_for :image do |image_field| %>
              <%= image_field.file_field :image, multiple: true %>
            <% end %>

            <% if @gig.images.present? %>
              <div class="row">
                <div class="col-lg-12 form-image">
                  <% @gig.images.each do |image| %>
                    <%= image_tag(image.image.thumb("130x130").url) %>
                    <%= link_to "Delete", image_destroy_path(image.imageable_id, gig: @gig.uid), class: "delete btn btn-danger btn-xs", method: :delete %>
                  <% end %>
                </div>
              </div>
            <% end %>

            <div class="form-group ">
              <%= f.submit class: "btn btn-t-primary btn-theme" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gigs/_gig_images.html.erb
<% if gig.images.present? %>
  <% gig.images.each do |image| %>
    <div data-thumb=<%= image.image.thumb("#{thumb}").url %>>
      <%= image_tag(image.image.thumb("#{thumb}").url) %>
    </div>
  <% end %>
<% end %>

app/views/gigs/_send_message.html.erb
<% if current_user.nil? %>
  <%= link_to "Send a message", new_gig_bid_path(@gig.uid), class: "btn btn-theme btn-line dark btn-block-xs" %>
<% elsif current_user != gig.user %>
  <a href="#" data-toggle="modal" data-target="#sendMessage" class="btn btn-theme btn-line dark btn-block-xs">Send a message</a>
<% else %>
  <%= link_to "Go to your profile", dashboard_path %>
<% end %>

app/views/gigs/edit.html.erb
<%= render partial: "gigs/gig_form", locals: { gig: @gig, url: gig_path(@gig.uid), form_name: "Edit Gig" } %>

app/views/gigs/index.html.erb
<div class="hero-header">
  <div class="inner-hero-header">
    <div class="container">
      <div class="relative">
        <%= form_tag search_all_gigs_path, class: "form-search-home", method: :get do |f| %>
          <h4 class="text-center">Getting help for your household jobs just got easier.</h4>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= label_tag "what" %>
                <%= text_field_tag :search, nil, placeholder: "gig name, keywords, or description", class: "form-control input-lg" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= label_tag "where" %>
                <%= text_field_tag :location, nil, placeholder: "zipcode, city, etc.", class: "form-control input-lg" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= submit_tag "Find gigs", class: "btn btn-t-primary btn-lg btn-theme btn-pill btn-block" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<!-- box simple static -->
<div class="block-section bg-color1">
  <div class="bg-color1 block-section">
    <div class="container text-center">
      <div class="white-space-15"></div>
      <h2>How It Works</h2>
      <hr>
      <div class="row">
        <div class="col-md-4">
          <div class="box-ic-center">
            <i class="fa fa-laptop ic-box"></i>
            <h4>Have a gig?</h4>
            <p>Post your gig. You’ll receive bids within minutes and be notified via email.</p>
            <%= link_to "Create a Gig", new_gig_path, class: "btn btn-sm btn-pill btn-theme btn-line dark" %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box-ic-center ">
            <i class="fa fa-envelope-o ic-box"></i>
            <h4>Receive Bids</h4>
            <p>Award the gig to the person of your choice and connect with them to set up your gig.</p>
            <%= link_to "Find People", search_all_users_path, class: "btn btn-sm btn-pill btn-theme btn-line dark" %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box-ic-center">
            <i class="fa fa-tablet ic-box"></i>
            <h4>Review</h4>
            <p>Write a review to let other users know what a great experience you had.</p>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-pill btn-theme btn-line dark" %>
          </div>
        </div>
      </div>
    </div>
  </div><!-- end block top -->
</div><!-- end box simple static -->

<!-- 
<div class="block-section bg-color1">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-4">
        <h3 class="font-2x "><%= User.count %></h3>
        <h4 class="color-text">Members</h4>
      </div>
      <div class="col-md-4">
        <h3 class="font-2x "><%= Gig.count %></h3>
        <h4 class="color-text">Gigs Posted</h4>
      </div>
      <div class="col-md-4">
        <h3 class="font-2x "><%= number_to_currency(Gig.all.to_a.sum(&:budget).to_i, precision: 0) %></h3>
        <h4 class="color-text">To be made</h4>
      </div>
    </div>
  </div>
</div> end box simple static -->

app/views/gigs/new.html.erb
<%= render partial: "gigs/gig_form", locals: { gig: @gig, url: nil, form_name: "Create a gig" } %>

app/views/gigs/search_all.html.erb
<div class="main-header">
  <div class="container">
    <div class="row">

      <div class="col-md-10">
        <%= form_tag search_all_gigs_path, class: "form-search-list", method: :get do |f| %>
          <div class="row">
            <div class="col-lg-4 ">
              <div class="form-group">
                <label class="color-white">what <small>(gig keywords, skills, etc.)</small></label>
                <%= text_field_tag :search, nil, value: params[:search], class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <label class="color-white">where <small>(city, state, zipcode, etc.)</small></label>
                <%= text_field_tag :location, nil, value: params[:location], class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <label class="color-white">minimum budget</label>
                <%= select_tag :min, options_for_select(Gig::SEARCH_RATE, params[:min]), class: "form-control", style: "width: 120px;" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <label class="hidden-xs">&nbsp;</label>
                <%= submit_tag "Find gigs", class: "btn btn-block btn-theme btn-success" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="body-content clearfix">
  <div class="bg-color2">
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <!-- box listing -->
          <div class="block-section-sm box-list-area">

            <!-- desc top -->
            <div class="row hidden-xs">
              <div class="col-sm-6  ">
                <p><strong class="color-black"><%= params[:search] %> jobs near <%= params[:location] %></strong></p>
              </div>
              <div class="col-sm-6">
                <p class="text-right">Jobs 1 to <%= @gigs.count %> of <%= @gigs.total_count %></p>
              </div>
            </div><!-- end desc top -->

            <!-- item list -->  
            <div class="box-list">
              <% @gigs.each do |gig| %>
                <div class="item">
                  <div class="row">
                    <div class="col-md-10">
                      <h3 class="no-margin-top"><%= link_to gig.name, gig_path(gig.uid), class: "gig-name" %></h3>
                      <h5>
                        <span class="color-black"><%= link_to gig.user.fullname.titleize, user_path(gig.user.uid) %></span> -
                        <span class="color-white-mute"> <%= gig.location %></span>
                      </h5>
                      <p class="text-truncate ">
                        <%= gig.description %>
                      </p>
                      <div>
                        <span class="color-white-mute"><%= gig.created_at.strftime("%b %d, %Y") %></span> - 
                        <span class="btn btn-xs btn-theme btn-warning"><%= gig.category.name %></span>
                      </div>
                    </div>
                    <div class="col-lg-1 hidden-sm hidden-xs">
                      <h4><span class="label label-success"><%= number_to_currency(gig.budget) %></span></h4>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <!-- pagination -->
            <%= paginate @gigs %>
          </div>

        </div>
        <div class="col-md-3">
          <div class="block-section-sm side-right">
            <div class="row">
              <div class="col-xs-6">
                <p><strong>Sort by: </strong></p>
              </div>
              <div class="col-xs-6">
                <p class="text-right">
                  <strong><%= sorting("Date") %></strong> - <a href="#" class="link-black"><strong><%= sorting("Budget") %></strong></a>
                </p>
              </div>
            </div>

            <div class="result-filter">
              <h5 class="no-margin-top font-bold margin-b-20 "><a href="#s_collapse_1" data-toggle="collapse">Categories <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i> </a></h5>
              <div class="collapse in" id="s_collapse_1">
                <div class="list-area">
                  <ul class="list-unstyled">
                    <li><%= link_to "All", params.merge(category: "All") %></li>
                    <li><%= link_to "Lawn Care", params.merge(category: 1) %></li>
                    <li><%= link_to "Home Improvement", params.merge(category: 2) %></li>
                    <li><%= link_to "General Labor", params.merge(category: 3) %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gigs/show.html.erb
 <div class="body-content clearfix">

  <!-- link top -->
  <div class="bg-color2 block-section-xs line-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 hidden-xs">
          <div>Job details :</div>
        </div>
        <div class="col-sm-6">
          <div class="text-right"><%= link_to "« Go back to job listings", "/gigs/search_all?utf8=✓&search=&location=Minneapolis&button=" %></div>
        </div>
      </div>
    </div>
  </div><!-- end link top -->

  <div class="bg-color2">
    <div class="container">
      <div class="row">
        <div class="col-md-9">

          <!-- box item details -->
          <div class="block-section box-item-details">

            <h2 class="title"><%= @gig.name %></h2>
            <div class="job-meta">
              <ul class="list-inline">
                <li><i class="fa fa-user"></i> <%= @gig.user.fullname.titleize %> (<%= @gig.user.username %>)</li>
                <li><i class="fa fa-map-marker"></i> <%= @gig.location %></li>
                <li><i class="fa fa-money"></i> <%= number_to_currency(@gig.budget) %></li>
                <li><i class="fa fa-calendar"></i> Posted on <%= @gig.created_at.strftime("%b %d, %Y") %></li>
              </ul>
            </div>
            <p><%= markdown(@gig.description) %></p>
            <div class="items-show">
              <%= render partial: "gigs/gig_images", locals: { gig: @gig, thumb: "500x500"} %>
            </div>
          </div>

        </div>
        <div class="col-md-3">

          <!-- box affix right -->
          <div class="block-section affix" id="affix-box">
            <div class="text-right">
              <%= render partial: "gigs/bid_button", locals: { gig: @gig, bid: @bid } %>
              <br>
              <br>
              <%= render partial: "gigs/send_message", locals: { gig: @gig } %>
            </div>
          </div><!-- box affix right -->

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal for bid button -->
<div class="modal fade" id="bidButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">You are bidding on <%= @gig.name %></h4>
      </div>
      <div class="modal-body">
        <%= form_for :bid, url: gig_bids_path(@gig.uid, @bid) do |f| %>
          <div class="form-group">
            <%= f.label :amount, "<h5>Bid</h5>".html_safe %>
            <%= f.text_field :amount, placeholder: "Enter your bid", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Tell the gig owner why they should choose you" %>
          </div>
          <div class="divider"></div>
          <%= f.submit "Submit Bid", class: "btn btn-success btn-theme" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- end Modal for bid button -->

<!-- Modal for send message -->
<% if current_user.present? %>
  <div class="modal fade" id="sendMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Send <%= @gig.user.firstname.capitalize %> a message about this gig</h4>
        </div>
        <div class="modal-body">
          <%= form_for :message, url: user_messages_path(@gig.user.uid), method: :post do |f| %>
            <%= f.hidden_field :gig_uid, value: @gig.uid %>
            <%= f.hidden_field :subject, value: "Message from #{current_user.username} about Gig ##{@gig.uid} - #{@gig.name}" %>
            <h5>Message</h5>
            <div class="form-group">
              <%= f.text_area :body, rows: 10, class: "form-control" %>
            </div>
            <%= f.submit "Send Message", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- end Modal for send message -->