config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :gigs, param: :uid do
    post :update_status
    resources :bids
    post :finish
    collection do
      get :search_all
    end
  end

  resources :users, param: :uid, only: [:show] do
    resources :reviews, only: [:new, :create, :show]
    resources :conversations do
      resources :messages, only: [:create]
    end
    collection do
      get :search_all
    end
  end

  get '/dashboard'  => 'users#dashboard'
  get '/about_us'   => 'pages#about_us'
  get '/howitworks' => 'pages#howitworks'
  
  post '/gigs/:gig_uid/bids/:bid_id/select_bid'   => 'gigs#select_bid',   as: :select_bid
  post '/gigs/:gig_uid/bids/:bid_id/deselect_bid' => 'gigs#deselect_bid', as: :deselect_bid
  post '/users/update_searchable' => 'users#update_searchable', as: :update_searchable
  post '/user/:user_uid/messages' => 'messages#new_message', as: :user_messages
  delete '/image/:imageable_id' => 'images#destroy', as: :image_destroy

  root 'gigs#index'
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline link-footer text-center-xs">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About Us", about_us_path %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production" %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-16135295-11', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/layouts/_header.html.erb
<header class="">
  <!-- main navbar -->
  <nav class="navbar navbar-default main-navbar hidden-sm hidden-xs">
    <div class="container">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li><%= link_to image_tag("https://dl.dropbox.com/s/8u16z6mfsr0jzq9/seekgig%20logo.png?dl=1"), root_path %></li>
          <li><%= link_to "Find a Gig", "/gigs/search_all?utf8=✓&search=&location=Minneapolis&button=" %></li>
          <li><%= link_to "Find People", search_all_users_path %></li>
          <li><%= link_to "How it Works", howitworks_path %></li>
          <li><%= link_to "Create a Gig", new_gig_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="link-btn"><%= link_to dashboard_path do %><span class="btn btn-theme btn-pill btn-xs btn-line">Dashboard</span><% end %></li>
            <li class="link-btn"><%= link_to  edit_user_registration_path do %><span class="btn btn-theme btn-pill btn-xs btn-line">Edit Profile</span><% end %></li>
            <li class="link-btn"><%= link_to  destroy_user_session_path, method: :delete do %><span class="btn btn-theme btn-pill btn-xs btn-line">Sign out</span><% end %></li>
          <% else %>
            <li class="link-btn"><%= link_to new_user_session_path do %><span class="btn btn-theme btn-pill btn-xs btn-line">Login</span><% end %></li>
            <li class="link-btn"><%= link_to new_user_registration_path do %><span class="btn btn-theme btn-pill btn-xs btn-line">Sign Up</span><% end %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav><!-- end main navbar -->

  <!-- mobile navbar -->
  <div class="container">
    <nav class="mobile-nav hidden-md hidden-lg">
      <a href="#" class="btn-nav-toogle first">
        <span class="bars"></span>
        Menu
      </a>
      <div class="mobile-nav-block">
        <h4>Navigation</h4>
        <a href="#" class="btn-nav-toogle">
          <span class="barsclose"></span>
          Close
        </a>

        <ul class="nav navbar-nav">
          <li class=""><a href="job_list.html"><strong>Find a Job</strong></a></li>
          <li class=""><a href="resume_list.html"><strong>Find Resumes</strong></a></li>
          <li  class=""><a href="job_post_1.html"><strong>Post a Job</strong></a></li>
          <li><a href="login.html"><strong>Login</strong></a></li>
          <li><a href="register.html"><strong>Register</strong></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Pages <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="about.html">About Us</a></li>
              <li><a href="contact.html">Contact Us</a></li>
              <li><a href="blog.html">Articles &amp; Blog</a></li>
              <li><a href="terms_privacy.html">Terms &amp; Privacy</a></li>
              <li><a href="error_404.html">Error 404</a></li>
              <li><a href="shortcode.html">Short Code</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Features <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="job_list.html">Find a Job</a></li>
              <li><a href="job_details.html">Job Details</a></li>
              <li><a href="resume_list.html">Find Resumes</a></li>
              <li><a href="resume_details.html">Resume Details</a></li>
              <li><a href="job_post_2.html">Post a Job</a></li>
              <li><a href="company_page.html">Company Profile</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </div><!-- mobile navbar -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seekgig</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <%= render 'toastr_rails/flash' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <%= render 'layouts/google_analytics' %>
</body>
</html>